-- Seed data for loan products
-- Run this after the initial migration

INSERT INTO products (id, name, bank, type, rate_apr, min_income, min_credit_score, tenure_min_months, tenure_max_months, processing_fee_pct, prepayment_allowed, disbursal_speed, docs_level, summary, faq, terms)
VALUES
  (
    '550e8400-e29b-41d4-a716-446655440001',
    'HDFC Personal Loan Express',
    'HDFC Bank',
    'personal',
    10.5,
    25000,
    700,
    12,
    60,
    1.5,
    true,
    'fast',
    'minimal',
    'Quick personal loan with minimal documentation. Perfect for salaried professionals looking for instant funds with flexible repayment options.',
    '[{"question": "What is the maximum loan amount?", "answer": "You can get up to ₹40 lakhs based on your income and credit profile."}, {"question": "How long does approval take?", "answer": "Approval is typically within 4 hours for existing HDFC customers."}, {"question": "Can I prepay the loan?", "answer": "Yes, prepayment is allowed after 6 months with no penalty."}]'::jsonb,
    '{"prepayment_penalty": "None after 6 months", "late_payment_fee": "2% of EMI amount", "processing_time": "4-24 hours", "eligibility_criteria": ["Age 21-60 years", "Minimum 2 years work experience", "Stable employment"], "required_documents": ["PAN Card", "Aadhaar Card", "Latest 3 months salary slips"]}'::jsonb
  ),
  (
    '550e8400-e29b-41d4-a716-446655440002',
    'SBI Education Loan',
    'State Bank of India',
    'education',
    7.5,
    0,
    650,
    36,
    180,
    0,
    true,
    'standard',
    'standard',
    'Comprehensive education loan for studies in India and abroad. Covers tuition, living expenses, and travel costs with interest subsidy for economically weaker sections.',
    '[{"question": "What expenses are covered?", "answer": "Tuition fees, hostel charges, examination fees, library fees, travel expenses, and purchase of books/equipment."}, {"question": "Is collateral required?", "answer": "No collateral for loans up to ₹7.5 lakhs. Above that, collateral is required."}, {"question": "When does repayment start?", "answer": "Repayment starts 1 year after course completion or 6 months after getting a job."}]'::jsonb,
    '{"prepayment_penalty": "None", "late_payment_fee": "1.5% per annum on overdue amount", "processing_time": "7-14 days", "eligibility_criteria": ["Indian national", "Secured admission in recognized institution", "Co-applicant (parent/guardian) required"], "required_documents": ["Admission letter", "Fee structure", "Mark sheets", "Income proof of co-applicant"]}'::jsonb
  ),
  (
    '550e8400-e29b-41d4-a716-446655440003',
    'ICICI Home Loan',
    'ICICI Bank',
    'home',
    8.4,
    40000,
    750,
    60,
    360,
    0.5,
    true,
    'standard',
    'extensive',
    'Affordable home loan with competitive interest rates. Special offers for women borrowers with additional 0.05% concession.',
    '[{"question": "What is the maximum loan-to-value ratio?", "answer": "Up to 90% for loans up to ₹30 lakhs, 80% for loans between ₹30-75 lakhs."}, {"question": "Are there any special offers?", "answer": "Women borrowers get 0.05% interest rate concession. Festive offers may apply."}, {"question": "Can I transfer my existing home loan?", "answer": "Yes, balance transfer facility is available with attractive rates."}]'::jsonb,
    '{"prepayment_penalty": "None for floating rate loans", "late_payment_fee": "2% per month on overdue EMI", "processing_time": "5-7 working days", "eligibility_criteria": ["Age 23-65 years", "Minimum 3 years total work experience", "Property should be legally clear"], "required_documents": ["Income proof", "Property documents", "Identity proof", "Bank statements"]}'::jsonb
  ),
  (
    '550e8400-e29b-41d4-a716-446655440004',
    'Axis Bank Car Loan',
    'Axis Bank',
    'vehicle',
    9.25,
    20000,
    700,
    12,
    84,
    1.0,
    true,
    'fast',
    'minimal',
    'Finance your dream car with Axis Bank. Quick approval process with up to 100% on-road funding for select models.',
    '[{"question": "What types of vehicles are covered?", "answer": "New cars, used cars (up to 5 years old), and two-wheelers."}, {"question": "What is the down payment requirement?", "answer": "Minimum 10% down payment for new cars. Used cars require 15-20%."}, {"question": "Is insurance mandatory?", "answer": "Yes, comprehensive insurance is mandatory for the loan tenure."}]'::jsonb,
    '{"prepayment_penalty": "2% of outstanding principal if prepaid within 12 months", "late_payment_fee": "₹500 per EMI bounce", "processing_time": "2-4 hours", "eligibility_criteria": ["Age 21-65 years", "Salaried or self-employed", "Valid driving license"], "required_documents": ["KYC documents", "Income proof", "Quotation from dealer"]}'::jsonb
  ),
  (
    '550e8400-e29b-41d4-a716-446655440005',
    'Bajaj Finserv Instant Loan',
    'Bajaj Finserv',
    'personal',
    12.0,
    22000,
    685,
    12,
    60,
    2.0,
    true,
    'instant',
    'minimal',
    'Get instant cash in your account within minutes. Fully digital process with no paperwork required for pre-approved customers.',
    '[{"question": "How fast is the disbursal?", "answer": "Funds are credited within 2 minutes for pre-approved customers."}, {"question": "What is the maximum loan amount?", "answer": "Up to ₹25 lakhs based on your credit profile and relationship with Bajaj."}, {"question": "Is there any hidden charges?", "answer": "No hidden charges. All fees are disclosed upfront in the loan agreement."}]'::jsonb,
    '{"prepayment_penalty": "4% of principal outstanding", "late_payment_fee": "₹800 per EMI bounce + GST", "processing_time": "2-5 minutes", "eligibility_criteria": ["Existing Bajaj Finserv customer or pre-approved offer", "Age 23-55 years", "Salaried professional"], "required_documents": ["OTP verification only for pre-approved customers"]}'::jsonb
  ),
  (
    '550e8400-e29b-41d4-a716-446655440006',
    'Kotak Mahindra Home Loan',
    'Kotak Mahindra Bank',
    'home',
    8.65,
    35000,
    720,
    60,
    240,
    0.5,
    true,
    'standard',
    'extensive',
    'Realize your dream of owning a home with Kotak''s flexible home loan. Get doorstep service and dedicated relationship manager.',
    '[{"question": "What is the maximum loan amount?", "answer": "Up to ₹5 crores based on property value and repayment capacity."}, {"question": "Can NRIs apply?", "answer": "Yes, NRIs can apply with additional documentation requirements."}, {"question": "Is top-up loan available?", "answer": "Yes, existing home loan customers can avail top-up loans at attractive rates."}]'::jsonb,
    '{"prepayment_penalty": "None for individual borrowers with floating rate", "late_payment_fee": "18% p.a. on overdue amount", "processing_time": "7-10 working days", "eligibility_criteria": ["Age 21-65 years", "Minimum income ₹35,000/month", "Clear CIBIL record"], "required_documents": ["Salary slips", "Form 16", "Property documents", "Bank statements"]}'::jsonb
  ),
  (
    '550e8400-e29b-41d4-a716-446655440007',
    'Tata Capital Personal Loan',
    'Tata Capital',
    'personal',
    11.25,
    25000,
    700,
    12,
    72,
    1.5,
    true,
    'fast',
    'minimal',
    'Trustworthy personal loans from the house of Tata. Transparent pricing with no hidden charges and flexible EMI options.',
    '[{"question": "What can I use this loan for?", "answer": "Wedding expenses, medical emergencies, home renovation, travel, debt consolidation, etc."}, {"question": "How do I check my eligibility?", "answer": "Use our online eligibility calculator or call our toll-free number."}, {"question": "Can I choose my EMI date?", "answer": "Yes, you can select your preferred EMI date between 1st and 28th of the month."}]'::jsonb,
    '{"prepayment_penalty": "3% after 12 EMIs", "late_payment_fee": "2% of EMI + GST", "processing_time": "24-48 hours", "eligibility_criteria": ["Age 23-58 years", "Minimum 1 year in current job", "Salaried or self-employed"], "required_documents": ["PAN Card", "Address proof", "3 months bank statement", "Salary slips"]}'::jsonb
  ),
  (
    '550e8400-e29b-41d4-a716-446655440008',
    'Punjab National Bank Vehicle Loan',
    'Punjab National Bank',
    'vehicle',
    8.85,
    18000,
    680,
    12,
    84,
    0.5,
    true,
    'standard',
    'standard',
    'Affordable vehicle financing from PNB. Special schemes for electric vehicles with additional interest concession.',
    '[{"question": "Is there any discount for EV purchases?", "answer": "Yes, 0.25% interest rate concession for electric vehicles."}, {"question": "What is the funding limit?", "answer": "Up to 85% of vehicle on-road price for new vehicles."}, {"question": "Can I include accessories in the loan?", "answer": "Yes, genuine accessories up to ₹50,000 can be included."}]'::jsonb,
    '{"prepayment_penalty": "1% of outstanding amount", "late_payment_fee": "2% per month on overdue EMI", "processing_time": "3-5 working days", "eligibility_criteria": ["Age 18-65 years", "Regular income source", "Good repayment track record"], "required_documents": ["KYC documents", "Income proof", "Vehicle quotation", "Bank statement"]}'::jsonb
  ),
  (
    '550e8400-e29b-41d4-a716-446655440009',
    'IDFC First Bank Credit Line',
    'IDFC First Bank',
    'credit_line',
    14.5,
    30000,
    720,
    6,
    36,
    0,
    true,
    'instant',
    'minimal',
    'Flexible credit line that you can use as and when needed. Pay interest only on utilized amount with zero processing fee.',
    '[{"question": "How is interest calculated?", "answer": "Interest is charged only on the amount you withdraw, calculated daily."}, {"question": "Can I repay and redraw?", "answer": "Yes, it''s a revolving credit line. You can repay and redraw multiple times."}, {"question": "What is the credit limit?", "answer": "Up to ₹10 lakhs based on your income and credit profile."}]'::jsonb,
    '{"prepayment_penalty": "None", "late_payment_fee": "₹500 per instance", "processing_time": "Instant approval", "eligibility_criteria": ["Age 21-60 years", "Minimum salary ₹30,000", "Good credit history"], "required_documents": ["Digital KYC", "Bank statement access"]}'::jsonb
  ),
  (
    '550e8400-e29b-41d4-a716-446655440010',
    'Bank of Baroda Education Loan',
    'Bank of Baroda',
    'education',
    7.75,
    0,
    600,
    60,
    180,
    0,
    true,
    'standard',
    'standard',
    'Vidya Lakshmi scheme compliant education loan. Interest subsidy available for economically weaker sections under CSIS scheme.',
    '[{"question": "What is the Vidya Lakshmi scheme?", "answer": "It''s a government portal where you can apply for education loans to multiple banks."}, {"question": "Is interest subsidy available?", "answer": "Yes, under Central Sector Interest Subsidy scheme for students from EWS families."}, {"question": "What courses are eligible?", "answer": "All courses in India recognized by competent authorities and select courses abroad."}]'::jsonb,
    '{"prepayment_penalty": "None", "late_payment_fee": "2% p.a. penal interest", "processing_time": "10-15 working days", "eligibility_criteria": ["Indian citizen", "Admission secured in recognized course", "Satisfactory academic record"], "required_documents": ["Admission proof", "Fee structure", "Academic records", "Co-applicant documents"]}'::jsonb
  ),
  (
    '550e8400-e29b-41d4-a716-446655440011',
    'Yes Bank Debt Consolidation Loan',
    'Yes Bank',
    'debt_consolidation',
    13.5,
    40000,
    730,
    12,
    60,
    1.5,
    true,
    'fast',
    'standard',
    'Consolidate multiple loans into one easy EMI. Simplify your finances and potentially save on interest costs.',
    '[{"question": "What debts can be consolidated?", "answer": "Credit card dues, personal loans, consumer durable loans, and other unsecured debts."}, {"question": "Will this improve my credit score?", "answer": "Timely repayments can help improve your credit score over time."}, {"question": "How much can I consolidate?", "answer": "Up to ₹50 lakhs depending on your repayment capacity."}]'::jsonb,
    '{"prepayment_penalty": "2% of outstanding after 6 months", "late_payment_fee": "₹750 per instance", "processing_time": "3-5 working days", "eligibility_criteria": ["Existing debt obligations", "Good repayment history", "Minimum salary ₹40,000"], "required_documents": ["Existing loan statements", "Bank statements", "Salary slips", "KYC documents"]}'::jsonb
  ),
  (
    '550e8400-e29b-41d4-a716-446655440012',
    'IndusInd Bank Premium Personal Loan',
    'IndusInd Bank',
    'personal',
    10.0,
    50000,
    750,
    12,
    60,
    1.0,
    true,
    'instant',
    'minimal',
    'Premium personal loan for high-income professionals. Enjoy preferential rates and dedicated relationship management.',
    '[{"question": "What makes this premium?", "answer": "Lower interest rates, higher loan amounts, dedicated RM, and priority processing."}, {"question": "What is the maximum loan amount?", "answer": "Up to ₹75 lakhs for eligible customers."}, {"question": "Is balance transfer available?", "answer": "Yes, you can transfer existing loans at attractive rates."}]'::jsonb,
    '{"prepayment_penalty": "2% after 12 EMIs", "late_payment_fee": "2% of EMI or ₹750 whichever is higher", "processing_time": "Same day for pre-approved", "eligibility_criteria": ["Age 25-58 years", "Minimum salary ₹50,000", "Credit score 750+"], "required_documents": ["Minimal - digital verification for pre-approved"]}'::jsonb
  ),
  (
    '550e8400-e29b-41d4-a716-446655440013',
    'Federal Bank Two-Wheeler Loan',
    'Federal Bank',
    'vehicle',
    9.99,
    15000,
    650,
    12,
    48,
    1.0,
    true,
    'fast',
    'minimal',
    'Easy financing for your two-wheeler purchase. Quick approval with minimal documentation and doorstep service.',
    '[{"question": "What two-wheelers are covered?", "answer": "All new scooters and motorcycles from authorized dealers."}, {"question": "What is the funding percentage?", "answer": "Up to 90% of on-road price for salaried individuals."}, {"question": "Is there any offer for students?", "answer": "Yes, special scheme for students with parent as co-applicant."}]'::jsonb,
    '{"prepayment_penalty": "None after 6 months", "late_payment_fee": "₹400 per bounce", "processing_time": "Same day", "eligibility_criteria": ["Age 18-60 years", "Regular income source", "Valid driving license"], "required_documents": ["KYC", "Income proof", "Dealer quotation"]}'::jsonb
  ),
  (
    '550e8400-e29b-41d4-a716-446655440014',
    'Canara Bank Home Loan',
    'Canara Bank',
    'home',
    8.35,
    30000,
    700,
    60,
    360,
    0.5,
    true,
    'standard',
    'extensive',
    'Affordable home loans from a trusted PSU bank. Special rates for women borrowers and eco-friendly homes.',
    '[{"question": "What is the interest rate for women?", "answer": "Women borrowers get 0.05% concession on applicable rates."}, {"question": "Is PMAY benefit available?", "answer": "Yes, eligible customers can avail PMAY interest subsidy."}, {"question": "What types of properties are covered?", "answer": "Ready properties, under-construction, plot purchase, and self-construction."}]'::jsonb,
    '{"prepayment_penalty": "Nil for floating rate loans", "late_payment_fee": "2% p.a. on overdue amount", "processing_time": "7-14 days", "eligibility_criteria": ["Age 18-65 years", "Stable income", "Clear title property"], "required_documents": ["Income proof", "Property papers", "Identity/Address proof", "Photos"]}'::jsonb
  ),
  (
    '550e8400-e29b-41d4-a716-446655440015',
    'MoneyTap Credit Line',
    'MoneyTap',
    'credit_line',
    15.0,
    20000,
    650,
    2,
    36,
    0,
    true,
    'instant',
    'minimal',
    'App-based personal credit line. Withdraw any amount from your approved limit anytime with instant transfer to bank account.',
    '[{"question": "How do I access funds?", "answer": "Simply open the app and transfer any amount to your bank account instantly."}, {"question": "What is the minimum withdrawal?", "answer": "You can withdraw as low as ₹3,000 at a time."}, {"question": "How is EMI calculated?", "answer": "You choose your EMI tenure (2-36 months) for each withdrawal separately."}]'::jsonb,
    '{"prepayment_penalty": "None", "late_payment_fee": "₹500 + GST per instance", "processing_time": "Instant", "eligibility_criteria": ["Age 21-57 years", "Minimum salary ₹20,000", "Smartphone with internet"], "required_documents": ["PAN", "Aadhaar", "Bank account linking"]}'::jsonb
  )
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  bank = EXCLUDED.bank,
  type = EXCLUDED.type,
  rate_apr = EXCLUDED.rate_apr,
  min_income = EXCLUDED.min_income,
  min_credit_score = EXCLUDED.min_credit_score,
  tenure_min_months = EXCLUDED.tenure_min_months,
  tenure_max_months = EXCLUDED.tenure_max_months,
  processing_fee_pct = EXCLUDED.processing_fee_pct,
  prepayment_allowed = EXCLUDED.prepayment_allowed,
  disbursal_speed = EXCLUDED.disbursal_speed,
  docs_level = EXCLUDED.docs_level,
  summary = EXCLUDED.summary,
  faq = EXCLUDED.faq,
  terms = EXCLUDED.terms,
  updated_at = NOW();





